FORMAT: 1A
HOST: https://viettrinh.xyz/

# Go - Echo skeleton

Sample documentation.

## Health [/health-check]

### Query health [GET]

Use to check the API status

+ Response 200 (application/json)

        {
            "status": "ok"
        }